### PR TITLE
Global navignation menu

### PR DESCRIPTION
**Pull request by pascualin**
I integrated the Global Navigation Menu on the sample pages, so users can use it as a reference implementation

### CODE REVIEW

**Comment by jsmecham** [comment]
There are some layout issues in IE11 (see screenshot).
bs_win10_ie_11 0

**Comment by jsmecham** [comment]
Also a minor issue in Firefox.

bs_win10_firefox_52 0

**Comment by pascualin** [comment]
Issues on Firefox and IE11 should be fixed now, could you please take a look @jsmecham ? Thanks!

**Comment by jsmecham** [comment]
Looks good! 👍

**Pull request merged**
